#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# zip
cd dist

mv save_all_s4p app

mkdir save_all_s4p
mv app save_all_s4p/
cp run.bat save_all_s4p/

zip -r save_all_s4p.zip save_all_s4p/
